include:
- file: /r4.2/gitlab-base.yml
  project: QubesOS/qubes-continuous-integration
- file: /r4.2/gitlab-host.yml
  project: QubesOS/qubes-continuous-integration
- file: /r4.2/gitlab-host-openqa.yml
  project: QubesOS/qubes-continuous-integration
- file: /r4.2/gitlab-vm-archlinux.yml
  project: QubesOS/qubes-continuous-integration

variables:
  CI_INSTALL_EXCLUDE: xen-qubes-vm xen-qubes-debug xen-qubes-debuginfo

