sudo: required
dist: trusty
language: generic
install: git clone https://github.com/QubesOS/qubes-builder ~/qubes-builder
script: ~/qubes-builder/scripts/travis-build
# keep the log under 4MB limit
env:
 - DIST_DOM0=fc20 USE_QUBES_REPO_VERSION=3.1 VERBOSE=0
 - DISTS_VM=fc23 USE_QUBES_REPO_VERSION=3.1 VERBOSE=0
 - DISTS_VM=fc24 USE_QUBES_REPO_VERSION=3.1 VERBOSE=0
 - DISTS_VM=jessie USE_QUBES_REPO_VERSION=3.1
matrix:
 allow_failures:
  - env: DISTS_VM=fc23 USE_QUBES_REPO_VERSION=3.1 VERBOSE=0
